name: WebIMService
services:
  mysql:
    image: 8.0.22
    container_name: webIM
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sxj045115
      - MYSQL_DATABASE=webIM
    volumes:
      - mysql-data: /var/lib/mysql
      - /app/myconf: /etc/mysql/conf.d
    restart: always
    networks:
      - webIM
  redis:
    image: redis
    container_name: webIM
    ports:
      - "6379:6379"
volumes:
  mysql-data:
networks:
  webIM: